### ISSUE TITLE
Add option to use plugin as a simple cursor replacement 

### ISSUE THREAD

**Issue by ronrdev** [vrtmrz/ninja-cursor#3]
Since obsidian switched to using the system cursor a plugin is needed to add back an optional styled cursor. I personally like the fat blue cursor of iAwriter. 

Option to go back to a custom cursor in Obsidian.
Option to turn off cursor movement effects. 

Adding an image from iAwriter just to show how the prominent cursor fits with the intention of this plugin. 
![iA Writer 01](https://user-images.githubusercontent.com/13022919/187332957-83fd9f1e-2ac2-42f7-bda5-7fcba3e326ef.png)

**Comment by vrtmrz** [comment]
Thank you for asking me!
Ninja-cursor can turn into as like that, by CSS-snippet.

Like this:
```css
/* iAWriter-ish style. */
.cursorWrapper .x-cursor {
    opacity: 1;
    background: #00bbff;
    width: 3px;
    left: -1px;
    top: -6px;
    height: calc(12px + var(--cursor-height));
    transition: opacity;
}

/* Disable movement effect */
.cursorWrapper .x-cursor::after {
    display: none;
}

/* Blinking */
.cursorWrapper .x-cursor0,
.cursorWrapper .x-cursor1 {
    animation: blink1 1s 0s both infinite;
}

@keyframes blink1 {
    0% {
        opacity: 1;
    }

    45% {
        opacity: 1;
    }

    50% {
        opacity: 0.2;
    }

    95% {
        opacity: 0;
    }

    100% {
        opacity: 0.2;
    }
}
```

Could you please try this CSS snippet?

**Comment by ronrdev** [comment]
Hello. Thanks for sharing the snippet. It works well enough for me.

I don't know if there is a way to make it more responsive. Just want to report two issues. The custom cursor does not follow scroll position, and it is slower to respond than the system cursor after typing each letter. I will have to comment out the blink because the system cursor is still visible causing distraction. 

https://user-images.githubusercontent.com/13022919/187514467-f621c180-67c9-4374-a159-7e6dc30a36ce.mp4

Also noticed this glitch. I understand this is just a fun plugin, so I can live with the issues.

https://user-images.githubusercontent.com/13022919/187516019-d4a656c0-2777-42e5-a8a7-6cd7527d9f87.mp4

Thanks again. Having a more prominent cursor helps me

**Comment by vrtmrz** [comment]
@ronrdev 
The scrolling issue is fixed at v0.0.5! 
And I am going to investigate the delay of cursor movement.

**Comment by ronrdev** [comment]
Awesome!
Also would it be possible to have different settings/css for light and dark mode? I can create a new issue if this is something you would like to add to the plugin. I just want to change the color, but people might want a toggle/different effects for light and dark mode as well.

**Comment by ronrdev** [comment]
After the latest update the ninja cursor is showing below the system cursor. I'm using the css snippet to recreate the iAwriter like cursor.

![Screenshot_2022-10-17_18-40-56](https://user-images.githubusercontent.com/13022919/196297197-4cb0180a-9aa7-4ab5-b421-cf25e18e6725.png)

**Comment by vrtmrz** [comment]
@ronrdev 

So sorry for missing replies! 
> Also would it be possible to have different settings/css for light and dark mode?

Yes, we can! We can make different styles between both modes. as below:

```css
/* The cursor colour in a light theme */
.theme-light .x-cursor {
    background: #00bbff;
}
/*The cursor colour in a dark theme */
.theme-dark .x-cursor {
    background: #ffbbff;
}
```
Just only make the scope narrow.

> After the latest update the ninja cursor is showing below the system cursor. I'm using the css snippet to recreate the iAwriter like cursor.

Owing to the v1.0 upgrade, we have to ignore the area where tabs are shown, otherwise we could not move the window. So we have to offset the cursor also in custom CSS.
Just as like below:
```
    top: calc( -6px - var(--header-height));
```
Could you please try this CSS again?

**Comment by ronrdev** [comment]
Thank you for sharing the css. It's working great and ninja cursor feels more responsive with the new release.

**Comment by PootieeTang** [comment]
Hello and thank you for suggesting these features @ronrdev, additionally because you're a fan of iA Writer you should check out the plugin called Stille as it focuses on the sentence you're struggling. But I do have a question for @vrtmrz, is there anyway you can help me with this issue? I am noot sure if its a css problem or something I need to disable on my end. Basically the IA cursor you provided above works great for me, but it slightly is a bit faster than the original cursor, when the IA cursor blinks you can faintly see the system cursor. 

https://user-images.githubusercontent.com/121781912/210195606-a58bd0b0-4a41-49b1-8c39-914ff19eef09.mp4

**Comment by vrtmrz** [comment]
Oh my dear, I am really sorry for missing this!

If you feel noisy with the default cursor, we can make that invisible with this CSS:
```css
.cm-editor * {
    caret-color: transparent !important;
}
```
